/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Format of the UpVotr configuration file.
 */
export interface UpVotrConfig {
  /**
   * Production and development server configuration
   */
  server?:
    | ServerConfig
    | {
        production: ServerConfig;
        development: ServerConfig;
      };
  /**
   * Configuration for the MySQL connection
   */
  mysql: {
    /**
     * Configuration for the database structure. Database MUST be cleared between changes to this configuration.
     */
    database?: {
      name?: string;
      /**
       * Table name mappings, for custom table names. Only use this setting if you know what you are doing.
       */
      tableMap?: {
        /**
         * Table name
         */
        [k: string]: string;
      };
    };
    /**
     * Login credentials for the database connection
     */
    login: {
      user: string;
      password: string;
    };
    /**
     * Whether or not to automatically configure the database using CREATE IF NOT EXISTS
     */
    autoconfigure?: boolean;
    /**
     * Configuration for pool connection
     */
    connection?: {
      connectionLimit?: number;
      host?: string;
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
}
/**
 * Server hostname and port
 */
export interface ServerConfig {
  hostname: string;
  port: number;
}
