/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Format of the UpVotr configuration file.
 */
export interface UpVotrConfig {
  /**
   * Production and development server configuration
   */
  server?:
    | ServerConfig
    | {
        production: ServerConfig;
        development: ServerConfig;
      };
}
/**
 * Server hostname and port
 */
export interface ServerConfig {
  hostname: string;
  port: number;
}
